# This file was generated by GoReleaser. DO NOT EDIT.
cask "ur-uploader" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "b928dff90ccef8792ca63e180957e200e91c09d445695c6b4bbe0c25ba53d1a0"
      url "https://github.com/KOU050223/ur-uploader/releases/download/v#{version}/ur-uploader_v#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "15c768fd5fb49e55b233d8f73e3cd84758a90a2610b4edd7e3a336d1cc1ec63f"
      url "https://github.com/KOU050223/ur-uploader/releases/download/v#{version}/ur-uploader_v#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2856da8ad88aeef8f3a85f77c470cf1f6c586c72d03a9d847e228fb5ee05cc23"
      url "https://github.com/KOU050223/ur-uploader/releases/download/v#{version}/ur-uploader_v#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "83d76072fc5c6a72c504f8c70c34deaa40b842e04c3c3155b408e6f21c023c35"
      url "https://github.com/KOU050223/ur-uploader/releases/download/v#{version}/ur-uploader_v#{version}_linux_arm64.tar.gz"
    end
  end

  name "ur-uploader"
  desc "unityroom へのゲームアップロードを自動化する非公式CLI"
  homepage "https://github.com/KOU050223/ur-uploader"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ur-uploader"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      # 未署名バイナリが Gatekeeper に隔離されるのを解除する
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ur-uploader"]
    end
  end

  # No zap stanza required

end
