# This file was generated by GoReleaser. DO NOT EDIT.
cask "ur-uploader" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "afd0a9e850a5a4a6713033dc8aeb76b16609309614aef6132a5e6daeef73a10e"
      url "https://github.com/KOU050223/ur-uploader/releases/download/v#{version}/ur-uploader_v#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "82de938699cc64f15a53a6fd2923039e6d76d7571f011b85d7a859d79a0cd9df"
      url "https://github.com/KOU050223/ur-uploader/releases/download/v#{version}/ur-uploader_v#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "72666aa960d5746df74f00b2b6cb98fbbcf862831fec3ab8bc0a97b5f0524b36"
      url "https://github.com/KOU050223/ur-uploader/releases/download/v#{version}/ur-uploader_v#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "440ba016d526c8da65da7c74a1612c2953ae337a0aa9b03d7dc39cee2ddea6f6"
      url "https://github.com/KOU050223/ur-uploader/releases/download/v#{version}/ur-uploader_v#{version}_linux_arm64.tar.gz"
    end
  end

  name "ur-uploader"
  desc "unityroom へのゲームアップロードを自動化する非公式CLI"
  homepage "https://github.com/KOU050223/ur-uploader"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ur-uploader"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      # 未署名バイナリが Gatekeeper に隔離されるのを解除する
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ur-uploader"]
    end
  end

  # No zap stanza required

end
